const { test, expect, apiStatus } = require('../fixtures.cjs');
test('cross-role claim, assignment, notes, status, close/reopen, archive and restoration', async ({ fx }) => {
  const owner = await fx.actor(); const agent = await fx.actor('AGENT'); const admin = await fx.actor('ADMIN'); const alternate = await fx.account('AGENT');
  const row = await fx.ticket(owner.user); const url = '/tickets/' + row.id;
  await agent.page.goto(url); await agent.page.getByRole('button', { name: 'Assign to me' }).click();
  await expect(agent.page.getByRole('button', { name: 'Unassign myself' })).toBeVisible();
  await agent.page.getByRole('button', { name: 'Unassign myself' }).click();
  await admin.page.goto(url); await admin.page.getByLabel('Assigned agent', { exact: true }).selectOption(alternate.id);
  await expect(admin.page.getByLabel('Assigned agent', { exact: true })).toHaveValue(alternate.id);
  await admin.page.getByLabel('Assigned agent', { exact: true }).selectOption(agent.user.id);
  await agent.page.reload(); await agent.page.getByLabel('Status', { exact: true }).selectOption('IN_PROGRESS');
  await expect(agent.page.getByLabel('Status', { exact: true })).toHaveValue('IN_PROGRESS');
  await agent.page.getByPlaceholder('Write a comment...').fill(fx.prefix + ' private internal note');
  await agent.page.getByRole('checkbox', { name: /Internal note/ }).check(); await agent.page.getByRole('button', { name: 'Post', exact: true }).click();
  await expect(agent.page.getByPlaceholder('Write a comment...')).toHaveValue('');
  await agent.page.getByRole('checkbox', { name: /Internal note/ }).uncheck();
  await agent.page.getByPlaceholder('Write a comment...').fill(fx.prefix + ' public response'); await agent.page.getByRole('button', { name: 'Post', exact: true }).click();
  await expect(agent.page.getByPlaceholder('Write a comment...')).toHaveValue('');
  await owner.page.goto(url); await expect(owner.page.getByText(fx.prefix + ' public response', { exact: true })).toBeVisible();
  await expect(owner.page.getByText(fx.prefix + ' private internal note', { exact: true })).toHaveCount(0);
  await agent.page.getByLabel('Priority', { exact: true }).selectOption('HIGH'); await expect(agent.page.getByLabel('Priority', { exact: true })).toHaveValue('HIGH');
  await agent.page.getByLabel('Status', { exact: true }).selectOption('RESOLVED'); await expect(agent.page.getByLabel('Status', { exact: true })).toHaveValue('RESOLVED');
  await agent.page.getByLabel('Status', { exact: true }).selectOption('CLOSED'); await agent.page.getByRole('button', { name: 'Yes, Close Ticket' }).click();
  await expect(agent.page.getByLabel('Priority', { exact: true })).toBeDisabled();
  expect(await apiStatus(agent.page, url, 'PATCH', { priority: 'LOW' })).toBe(422);
  await agent.page.getByLabel('Status', { exact: true }).selectOption('OPEN'); await expect(agent.page.getByLabel('Status', { exact: true })).toHaveValue('OPEN');
  await agent.page.getByLabel('Status', { exact: true }).selectOption('IN_PROGRESS'); await expect(agent.page.getByLabel('Status', { exact: true })).toHaveValue('IN_PROGRESS');
  await agent.page.getByLabel('Status', { exact: true }).selectOption('RESOLVED'); await expect(agent.page.getByLabel('Status', { exact: true })).toHaveValue('RESOLVED');
  await agent.page.getByRole('button', { name: 'Archive ticket', exact: true }).click(); await agent.page.getByRole('dialog', { name: 'Archive this ticket?', exact: true }).getByRole('button', { name: 'Move to Archived', exact: true }).click();
  await expect(agent.page).toHaveURL(/\/tickets\/archived$/);
  await agent.page.getByRole('row', { name: 'Open ' + row.title, exact: true }).click();
  await expect(agent.page.getByRole('heading', { name: 'Archived work item' })).toBeVisible();
  await expect(agent.page.getByPlaceholder('Write a comment...')).toHaveCount(0);
  expect(await apiStatus(agent.page, url + '/restore', 'PATCH', {})).toBe(403);
  await admin.page.goto(url); await admin.page.getByRole('button', { name: 'Restore', exact: true }).click();
  await admin.page.getByRole('dialog', { name: 'Restore this ticket?', exact: true }).getByRole('button', { name: 'Restore to active work', exact: true }).click();
  await expect(admin.page).toHaveURL(/\/tickets$/);
  await admin.page.getByRole('row', { name: 'Open ' + row.title, exact: true }).click();
  await expect(admin.page.getByRole('heading', { name: 'Archived work item' })).toHaveCount(0);
  expect((await fx.db.ticket.findUniqueOrThrow({ where: { id: row.id } })).status).toBe('RESOLVED');
});
