const { test, expect } = require('../fixtures.cjs');
test('saved views apply/update/delete; shortcuts reorder through the browser', async ({ fx }) => {
  const { page, user } = await fx.actor(); const row = await fx.ticket(user); await page.goto('/tickets');
  await page.getByLabel('Status', { exact: true }).selectOption('OPEN'); await page.getByRole('button', { name: 'Save current view' }).click();
  const name = fx.prefix + ' Open'; await page.getByLabel('View name').fill(name); await page.getByRole('button', { name: 'Save view name' }).click();
  await expect(page).toHaveURL(/\/saved-views\//); await expect(page.getByRole('row', { name: 'Open ' + row.title, exact: true })).toBeVisible();
  await page.getByLabel('Priority', { exact: true }).selectOption('MEDIUM'); await page.getByRole('button', { name: 'Update saved view' }).click();
  await expect(page.getByText(/Active view:/)).not.toContainText('Unsaved filter changes');
  await page.getByRole('button', { name: 'Add to shortcuts' }).click(); await expect(page.getByText('Preference saved.', { exact: true })).toBeVisible();
  await page.goto('/settings?section=shortcuts'); await page.getByLabel('Shortcut destination').selectOption('route:SUMMARY'); await page.getByRole('button', { name: 'Add shortcut' }).click();
  await expect(page.getByText('Personal shortcuts saved.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Move Summary up', exact: true }).click();
  await expect.poll(async () => (await fx.db.userShortcut.findFirstOrThrow({ where: { userId: user.id, position: 0 } })).routeKey).toBe('SUMMARY');
  const view = await fx.db.savedTicketView.findFirstOrThrow({ where: { userId: user.id } });
  await page.goto('/saved-views/' + view.id); await page.getByRole('button', { name: 'Delete view', exact: true }).click(); await page.getByRole('button', { name: 'Confirm delete view' }).click();
  await expect(page).toHaveURL(/\/tickets$/); expect(await fx.db.userShortcut.count({ where: { savedViewId: view.id } })).toBe(0);
});

test('watched and archived scopes survive saved-view navigation', async ({ fx }) => {
  const owner = await fx.actor(); const admin = await fx.actor('ADMIN');
  const watched = await fx.ticket(owner.user, { status: 'RESOLVED' }); const other = await fx.ticket(owner.user);
  await owner.page.goto('/tickets/' + watched.id);
  await owner.page.getByRole('button', { name: 'Watch ticket', exact: true }).click();
  await expect(owner.page.getByRole('button', { name: 'Stop watching', exact: true })).toBeVisible();
  await owner.page.goto('/tickets'); await owner.page.getByRole('checkbox', { name: 'Watched by me' }).check();
  await expect(owner.page.getByRole('row', { name: 'Open ' + watched.title, exact: true })).toBeVisible();
  await expect(owner.page.getByRole('row', { name: 'Open ' + other.title, exact: true })).toHaveCount(0);
  await owner.page.getByRole('button', { name: 'Save current view' }).click(); await owner.page.getByLabel('View name').fill(fx.prefix + ' Watched');
  await owner.page.getByRole('button', { name: 'Save view name' }).click(); await expect(owner.page).toHaveURL(/\/saved-views\//);
  await owner.page.reload(); await expect(owner.page.getByRole('checkbox', { name: 'Watched by me' })).toBeChecked();
  await expect(owner.page.getByRole('row', { name: 'Open ' + other.title, exact: true })).toHaveCount(0);
  await admin.page.goto('/tickets/' + watched.id); await admin.page.getByRole('button', { name: 'Archive ticket', exact: true }).click();
  await admin.page.getByRole('dialog').getByRole('button', { name: 'Move to Archived', exact: true }).click();
  await expect(admin.page).toHaveURL(/\/tickets\/archived$/);
  await expect(admin.page.getByRole('table', { name: 'Archived work items' }).getByRole('row', { name: 'Open ' + watched.title, exact: true })).toBeVisible();
  await owner.page.goto('/tickets/archived'); await owner.page.getByRole('checkbox', { name: 'Watched by me' }).check();
  await owner.page.getByRole('button', { name: 'Save current view' }).click(); await owner.page.getByLabel('View name').fill(fx.prefix + ' Archived');
  await owner.page.getByRole('button', { name: 'Save view name' }).click(); await expect(owner.page).toHaveURL(/\/saved-views\//);
  await owner.page.reload(); await expect(owner.page.getByRole('row', { name: 'Open ' + watched.title, exact: true })).toBeVisible();
  await expect(owner.page.getByRole('row', { name: 'Open ' + other.title, exact: true })).toHaveCount(0);
  const saved = await fx.db.savedTicketView.findFirstOrThrow({ where: { userId: owner.user.id, scope: 'ARCHIVED' } });
  expect(saved.filters.watchedByMe).toBe(true);
});
test('role-specific search, keyboard navigation, Summary, Reports and synthetic CSV', async ({ fx }) => {
  const owner = await fx.actor(); const agent = await fx.actor('AGENT'); const admin = await fx.actor('ADMIN'); const other = await fx.account();
  const own = await fx.ticket(owner.user, { assignedToId: agent.user.id }); const foreign = await fx.ticket(other);
  await owner.page.goto('/dashboard'); await expect(owner.page.getByRole('heading', { name: 'My Summary', exact: true })).toBeVisible();
  await agent.page.goto('/dashboard'); await expect(agent.page.getByRole('heading', { name: 'My Work Summary', exact: true })).toBeVisible();
  await admin.page.goto('/dashboard'); await expect(admin.page.getByRole('heading', { name: 'System Summary', exact: true })).toBeVisible();
  const search = owner.page.getByRole('combobox', { name: /Search/i }); await search.fill(fx.prefix);
  await expect(owner.page.getByRole('listbox', { name: 'Search suggestions' })).toBeVisible();
  await expect(owner.page.getByRole('option').filter({ hasText: own.title })).toBeVisible();
  await search.press('ArrowDown'); await search.press('Enter'); await expect(owner.page).toHaveURL(new RegExp('/tickets/' + own.id + '$'));
  await owner.page.goto('/search?q=' + encodeURIComponent(fx.prefix));
  await expect(owner.page.getByRole('link', { name: new RegExp(own.title) })).toBeVisible();
  await expect(owner.page.getByRole('link', { name: new RegExp(foreign.title) })).toHaveCount(0);
  await owner.page.goto('/reports'); await expect(owner.page).toHaveURL(/\/dashboard$/);
  await agent.page.goto('/reports'); await expect(agent.page.getByRole('heading', { name: 'My Reports', exact: true })).toBeVisible();
  await admin.page.goto('/reports'); await expect(admin.page.getByRole('heading', { name: 'Service Desk Reports', exact: true })).toBeVisible();
  await admin.page.getByLabel('Search', { exact: true }).fill(fx.prefix); await admin.page.getByRole('button', { name: 'Apply Filters' }).click();
  const downloadPromise = admin.page.waitForEvent('download'); await admin.page.getByRole('button', { name: 'Export authorized report CSV' }).click();
  const download = await downloadPromise; const chunks = []; for await (const chunk of await download.createReadStream()) chunks.push(chunk);
  const csv = Buffer.concat(chunks).toString('utf8'); expect(csv).toContain(fx.prefix); expect(csv.includes(fx.credential)).toBe(false); expect(csv).not.toMatch(/Bearer |postgresql:\/\//); await download.delete();
});
