ALTER TYPE "TicketCategory" RENAME TO "TicketCategory_legacy";
CREATE TYPE "TicketCategory" AS ENUM ('INTERNET_NETWORK','VPN','PC_LAPTOP','PRINTER_SCANNER','ACCOUNTS_ACCESS','EMAIL','SOFTWARE_APPLICATION','SERVER_SYSTEM','REQUESTS','SECURITY','OTHERS');
ALTER TABLE "tickets" ALTER COLUMN "category" DROP DEFAULT;
ALTER TABLE "tickets" ALTER COLUMN "category" TYPE "TicketCategory" USING (CASE "category"::text WHEN 'IT' THEN 'INTERNET_NETWORK' WHEN 'HR' THEN 'REQUESTS' WHEN 'BILLING' THEN 'REQUESTS' WHEN 'GENERAL' THEN 'OTHERS' WHEN 'OTHER' THEN 'OTHERS' WHEN 'INTERNET_NETWORK' THEN 'INTERNET_NETWORK' WHEN 'VPN' THEN 'VPN' WHEN 'PC_LAPTOP' THEN 'PC_LAPTOP' WHEN 'PRINTER_SCANNER' THEN 'PRINTER_SCANNER' WHEN 'ACCOUNTS_ACCESS' THEN 'ACCOUNTS_ACCESS' WHEN 'EMAIL' THEN 'EMAIL' WHEN 'SOFTWARE_APPLICATION' THEN 'SOFTWARE_APPLICATION' WHEN 'SERVER_SYSTEM' THEN 'SERVER_SYSTEM' WHEN 'REQUESTS' THEN 'REQUESTS' WHEN 'SECURITY' THEN 'SECURITY' WHEN 'OTHERS' THEN 'OTHERS' ELSE 'OTHERS' END)::"TicketCategory";
ALTER TABLE "tickets" ALTER COLUMN "category" SET DEFAULT 'OTHERS';
DROP TYPE "TicketCategory_legacy";
