const router = require('express').Router();
const auth = require('../../middleware/authenticate');
const authorize = require('../../middleware/authorize');
const uuid = require('../../middleware/validateUuidParam');
const validate = require('../../middleware/validate');
const asyncHandler = require('../../utils/asyncHandler');
const AppError = require('../../utils/AppError');
const service = require('./department.service');
const schema = require('./department.schema');
router.use(auth);
router.use((req, res, next) => { res.set('Cache-Control', 'private, no-store'); next(); });
router.get('/options', validate(schema.options, 'query'), asyncHandler(async (req, res) => res.json({ success: true, data: await service.list(req.query, true) })));
router.use(authorize('ADMIN'));
router.get('/', validate(schema.list, 'query'), asyncHandler(async (req, res) => res.json({ success: true, data: await service.list(req.query) })));
router.get('/:id/members', uuid('id'), validate(schema.members, 'query'), asyncHandler(async (req, res) => res.json({ success: true, data: await service.members(req.params.id, req.query) })));
router.post('/', validate(schema.create), asyncHandler(async (req, res) => res.status(201).json({ success: true, data: await service.create(req.user, req.body, req.requestId) })));
for (const action of ['update', 'status', 'merge']) router.patch(`/:id/${action}`, uuid('id'), validate(schema[action]), asyncHandler(async (req, res) => res.json({ success: true, data: await service[action](req.user, req.params.id, req.body, req.requestId) })));
router.patch('/users/:id', uuid('id'), validate(schema.assign), asyncHandler(async (req, res) => res.json({ success: true, data: await service.assign(req.user, req.params.id, req.body, req.requestId) })));
router.use((error, req, res, next) => next(error instanceof AppError ? error : new AppError('Department operation unavailable', 503)));
module.exports = router;
